// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_compVarImpReg
List Rcpp_compVarImpReg(NumericMatrix x, NumericVector y, int nsample, int mdim, int nTree, int nPerm, IntegerMatrix lDaughter, IntegerMatrix rDaughter, IntegerMatrix nodestatus, NumericMatrix split, NumericMatrix nodepred, IntegerMatrix splitVar, IntegerMatrix inm, IntegerVector ndbigtree, IntegerVector cat, int maxcat);
RcppExport SEXP vita_Rcpp_compVarImpReg(SEXP xSEXP, SEXP ySEXP, SEXP nsampleSEXP, SEXP mdimSEXP, SEXP nTreeSEXP, SEXP nPermSEXP, SEXP lDaughterSEXP, SEXP rDaughterSEXP, SEXP nodestatusSEXP, SEXP splitSEXP, SEXP nodepredSEXP, SEXP splitVarSEXP, SEXP inmSEXP, SEXP ndbigtreeSEXP, SEXP catSEXP, SEXP maxcatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< int >::type mdim(mdimSEXP);
    Rcpp::traits::input_parameter< int >::type nTree(nTreeSEXP);
    Rcpp::traits::input_parameter< int >::type nPerm(nPermSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type lDaughter(lDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rDaughter(rDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nodestatus(nodestatusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type split(splitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nodepred(nodepredSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type splitVar(splitVarSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type inm(inmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndbigtree(ndbigtreeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cat(catSEXP);
    Rcpp::traits::input_parameter< int >::type maxcat(maxcatSEXP);
    __result = Rcpp::wrap(Rcpp_compVarImpReg(x, y, nsample, mdim, nTree, nPerm, lDaughter, rDaughter, nodestatus, split, nodepred, splitVar, inm, ndbigtree, cat, maxcat));
    return __result;
END_RCPP
}
// Rcpp_compVarImpCL
List Rcpp_compVarImpCL(NumericMatrix x, IntegerVector y, int nsample, int mdim, int nTree, int nclass, IntegerMatrix lDaughter, IntegerMatrix rDaughter, IntegerMatrix nodestatus, NumericMatrix xbestsplit, IntegerMatrix nodeclass, IntegerMatrix bestvar, IntegerMatrix inbag, IntegerVector ndbigtree, IntegerVector cat, int maxcat);
RcppExport SEXP vita_Rcpp_compVarImpCL(SEXP xSEXP, SEXP ySEXP, SEXP nsampleSEXP, SEXP mdimSEXP, SEXP nTreeSEXP, SEXP nclassSEXP, SEXP lDaughterSEXP, SEXP rDaughterSEXP, SEXP nodestatusSEXP, SEXP xbestsplitSEXP, SEXP nodeclassSEXP, SEXP bestvarSEXP, SEXP inbagSEXP, SEXP ndbigtreeSEXP, SEXP catSEXP, SEXP maxcatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< int >::type mdim(mdimSEXP);
    Rcpp::traits::input_parameter< int >::type nTree(nTreeSEXP);
    Rcpp::traits::input_parameter< int >::type nclass(nclassSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type lDaughter(lDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rDaughter(rDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nodestatus(nodestatusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xbestsplit(xbestsplitSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nodeclass(nodeclassSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type bestvar(bestvarSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type inbag(inbagSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndbigtree(ndbigtreeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cat(catSEXP);
    Rcpp::traits::input_parameter< int >::type maxcat(maxcatSEXP);
    __result = Rcpp::wrap(Rcpp_compVarImpCL(x, y, nsample, mdim, nTree, nclass, lDaughter, rDaughter, nodestatus, xbestsplit, nodeclass, bestvar, inbag, ndbigtree, cat, maxcat));
    return __result;
END_RCPP
}
// Rcpp_VarImpCVLReg
List Rcpp_VarImpCVLReg(NumericMatrix x_l, NumericVector y_l, int nsample, int mdim, int nTree, int nPerm, IntegerMatrix lDaughter, IntegerMatrix rDaughter, IntegerMatrix nodestatus, NumericMatrix split, NumericMatrix nodepred, IntegerMatrix splitVar, IntegerVector ndbigtree, IntegerVector cat, int maxcat);
RcppExport SEXP vita_Rcpp_VarImpCVLReg(SEXP x_lSEXP, SEXP y_lSEXP, SEXP nsampleSEXP, SEXP mdimSEXP, SEXP nTreeSEXP, SEXP nPermSEXP, SEXP lDaughterSEXP, SEXP rDaughterSEXP, SEXP nodestatusSEXP, SEXP splitSEXP, SEXP nodepredSEXP, SEXP splitVarSEXP, SEXP ndbigtreeSEXP, SEXP catSEXP, SEXP maxcatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_l(x_lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_l(y_lSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< int >::type mdim(mdimSEXP);
    Rcpp::traits::input_parameter< int >::type nTree(nTreeSEXP);
    Rcpp::traits::input_parameter< int >::type nPerm(nPermSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type lDaughter(lDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rDaughter(rDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nodestatus(nodestatusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type split(splitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nodepred(nodepredSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type splitVar(splitVarSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndbigtree(ndbigtreeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cat(catSEXP);
    Rcpp::traits::input_parameter< int >::type maxcat(maxcatSEXP);
    __result = Rcpp::wrap(Rcpp_VarImpCVLReg(x_l, y_l, nsample, mdim, nTree, nPerm, lDaughter, rDaughter, nodestatus, split, nodepred, splitVar, ndbigtree, cat, maxcat));
    return __result;
END_RCPP
}
// Rcpp_VarImpCVLCL
List Rcpp_VarImpCVLCL(NumericMatrix x_l, IntegerVector y_l, int nsample, int mdim, int nTree, int nclass, IntegerMatrix lDaughter, IntegerMatrix rDaughter, IntegerMatrix nodestatus, NumericMatrix xbestsplit, IntegerMatrix nodeclass, IntegerMatrix bestvar, IntegerVector ndbigtree, IntegerVector cat, int maxcat);
RcppExport SEXP vita_Rcpp_VarImpCVLCL(SEXP x_lSEXP, SEXP y_lSEXP, SEXP nsampleSEXP, SEXP mdimSEXP, SEXP nTreeSEXP, SEXP nclassSEXP, SEXP lDaughterSEXP, SEXP rDaughterSEXP, SEXP nodestatusSEXP, SEXP xbestsplitSEXP, SEXP nodeclassSEXP, SEXP bestvarSEXP, SEXP ndbigtreeSEXP, SEXP catSEXP, SEXP maxcatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_l(x_lSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y_l(y_lSEXP);
    Rcpp::traits::input_parameter< int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< int >::type mdim(mdimSEXP);
    Rcpp::traits::input_parameter< int >::type nTree(nTreeSEXP);
    Rcpp::traits::input_parameter< int >::type nclass(nclassSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type lDaughter(lDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type rDaughter(rDaughterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nodestatus(nodestatusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xbestsplit(xbestsplitSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nodeclass(nodeclassSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type bestvar(bestvarSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndbigtree(ndbigtreeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cat(catSEXP);
    Rcpp::traits::input_parameter< int >::type maxcat(maxcatSEXP);
    __result = Rcpp::wrap(Rcpp_VarImpCVLCL(x_l, y_l, nsample, mdim, nTree, nclass, lDaughter, rDaughter, nodestatus, xbestsplit, nodeclass, bestvar, ndbigtree, cat, maxcat));
    return __result;
END_RCPP
}
